name: CI

on:
  push:

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.7", "3.8", "3.9", "3.10", "3.11"]
        exclude:
          - os: ubuntu-latest
            python-version: "2.7"
          - os: ubuntu-latest
            python-version: "3.5"
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          conda init bash
          exec bash
          conda create -n test-environment python=${{ matrix.python-version }} cython numpy pandas scipy scikit-learn pytest
          conda activate test-environment

      - name: Install
        run: |
          conda init bash
          exec bash
          conda activate test-environment
          git submodule update --init --recursive
          make TARGET=NEHALEM
          python setup.py bdist_wheel
          pip install dist/*.whl

      - name: Test
        run: |
          conda init bash
          exec bash
          conda activate test-environment
          pytest
