name: CI

on:
  push:

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.7", "3.8", "3.9", "3.10", "3.11"]
        exclude:
          - os: ubuntu-latest
            python-version: "2.7"
          - os: ubuntu-latest
            python-version: "3.5"
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}
          activate-environment: test-environment
          environment-file: environment.yml
          auto-activate-base: false

      - name: Install and Test
        shell: bash -l {0}
        run: |
          git submodule update --init --recursive
          make TARGET=NEHALEM
          python setup.py bdist_wheel
          pip install dist/*.whl
          pytest
